import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/src/components/ui/toaster";
import { EdgeStoreProvider } from "@/src/lib/edgestore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <meta property="og:title" content="Budgetease" />
      <meta property="og:description" content="Découvrez notre plateforme de budgetisation" />
      <meta property="og:image" content="/dashboard.png" />
      <meta property="og:url" content="/dashboard.png" />
      <meta property="og:type" content="website" />
    </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans  antialiased `}
      >
        <Toaster />
        <EdgeStoreProvider>{children}</EdgeStoreProvider>

      </body>
    </html>
  );
}
